master: user_test.sh: check for warning occurs first time, second time warning is an error.

diff --git a/bin/user_test.sh.in b/bin/user_test.sh.in
--- a/bin/user_test.sh.in
+++ b/bin/user_test.sh.in
@@ -20,18 +20,29 @@ then
 	exit 1
 fi
 user_test="$1"
-if @python3_executable@ $user_test
+if @python3_executable@ $user_test >& user_test.$$
 then
-	echo 'user_test.sh: OK'
-	exit 0
+	cat user_test.$$
+	if ! grep 'warning:' user_test.$$ > /dev/null
+	then
+		rm user_test.$$
+		echo 'user_test.sh: OK'
+		exit 0
+	fi
 fi
 echo 'First try failed, re-running test with a different random seed:'
 echo 'sleep 1'
 sleep 1
-if @python3_executable@ $user_test
+if @python3_executable@ $user_test >& user_test.$$
 then
-	echo 'user_test.sh: OK'
-	exit 0
+	cat user_test.$$
+	if ! grep 'warning:' user_test.$$ > /dev/null
+	then
+		rm user_test.$$
+		echo 'user_test.sh: OK'
+		exit 0
+	fi
 fi
-echo 'user_test.sh: Error'
+rm user_test.$$
+echo 'user_test.sh: Error or warning.'
 exit 1
